cadastros/urls.py
from django.urls import path
from . import views
from .views import CategoriaCreate, CategoriaDelete, CategoriaDetail, CategoriaList, CategoriaUpdate, ClienteCreate, ClienteDelete, ClienteDetail, ClienteList, ClienteUpdate, FabricanteCreate, FabricanteDelete, FabricanteDetail, FabricanteList, FabricanteUpdate, FornecedorCreate, FornecedorUpdate, FornecedorList, FornecedorDelete, FornecedorDetail, FuncionarioCreate, FuncionarioDelete, FuncionarioDetail, FuncionarioList, FuncionarioUpdate, MarcaCreate, MarcaDelete, MarcaDetail, MarcaList, MarcaUpdate, ProdutoCreate, ProdutoDelete, ProdutoDetail, ProdutoList, ProdutoUpdate
from .views import ProdutoPedidoList
from .views import ClienteCreate, ClienteUpdate, ClienteList, ClienteDelete
from .views import PedidoCreate, PedidoList, PedidoDelete
from .views import CarrinhoCreate, CarrinhoList, CarrinhoUpdate, CarrinhoDelete
from .views import ClienteAutocomplete
from .views import ProdutoAutocomplete

urlpatterns = [

    path("cadastrar/fornecedor/", FornecedorCreate.as_view(), name="cadastrar-fornecedor"),
    path("cadastrar/fabricante/", FabricanteCreate.as_view(), name="cadastrar-fabricante"),
    path("cadastrar/marca/", MarcaCreate.as_view(), name="cadastrar-marca"),
    path("cadastrar/categoria/", CategoriaCreate.as_view(), name="cadastrar-categoria"),
    path("cadastrar/cliente/", ClienteCreate.as_view(), name="cadastrar-cliente"),
    path("cadastrar/funcionario/", FuncionarioCreate.as_view(), name="cadastrar-funcionario"),
    path("cadastrar/produto/", ProdutoCreate.as_view(), name="cadastrar-produto"),
    path("cadastrar/pedido", PedidoCreate.as_view(), name="cadastrar-pedido"),
    path("cadastrar/carrinho", CarrinhoCreate.as_view(), name="cadastrar-carrinho"),

    path("editar/fornecedor/<int:pk>/", FornecedorUpdate.as_view(), name="editar-fornecedor"),
    path("editar/fabricante/<int:pk>/", FabricanteUpdate.as_view(), name="editar-fabricante"),
    path("editar/marca/<int:pk>/", MarcaUpdate.as_view(), name="editar-marca"),
    path("editar/categoria/<int:pk>/", CategoriaUpdate.as_view(), name="editar-categoria"),
    path("editar/cliente/<int:pk>/", ClienteUpdate.as_view(), name="editar-cliente"),
    path("editar/funcionario/<int:pk>/", FuncionarioUpdate.as_view(), name="editar-funcionario"),
    path("editar/produto/<int:pk>/", ProdutoUpdate.as_view(), name="editar-produto"),
    path("editar/carrinho/<int:pk>/", CarrinhoUpdate.as_view(), name="editar-carrinho"),

    path("excluir/fornecedor/<int:pk>/", FornecedorDelete.as_view(), name="excluir-fornecedor"),
    path("excluir/fabricante/<int:pk>/", FabricanteDelete.as_view(), name="excluir-fabricante"),
    path("excluir/marca/<int:pk>/", MarcaDelete.as_view(), name="excluir-marca"),
    path("excluir/categoria/<int:pk>/", CategoriaDelete.as_view(), name="excluir-categoria"),
    path("excluir/cliente/<int:pk>/", ClienteDelete.as_view(), name="excluir-cliente"),
    path("excluir/funcionario/<int:pk>/", FuncionarioDelete.as_view(), name="excluir-funcionario"),
    path("excluir/produto/<int:pk>/", ProdutoDelete.as_view(), name="excluir-produto"),
    path("excluir/pedido/<int:pk>/", PedidoDelete.as_view(), name="excluir-pedido"),
    path("excluir/carrinho/<int:pk>/", CarrinhoDelete.as_view(), name="excluir-carrinho"),

    path("listar/fornecedor/", FornecedorList.as_view(), name="listar-fornecedor"),
    path("listar/fabricante/", FabricanteList.as_view(), name="listar-fabricante"),
    path("listar/marca/", MarcaList.as_view(), name="listar-marca"),
    path("listar/categoria/", CategoriaList.as_view(), name="listar-categoria"),
    path("listar/cliente/", ClienteList.as_view(), name="listar-cliente"),
    path("listar/funcionario/", FuncionarioList.as_view(), name="listar-funcionario"),
    path("listar/produto/", ProdutoList.as_view(), name="listar-produto"),
    path("listar/pedido", PedidoList.as_view(), name="listar-pedido"),
    path("listar/carrinho", CarrinhoList.as_view(), name="listar-carrinho"),
    path("listar/produtos/pedido/<int:pk_pedido>/", ProdutoPedidoList.as_view(), name="listar-produtos-pedido"),

    path("detalhar/fornecedor/<int:pk>/",
         FornecedorDetail.as_view(), name="detalhar-fornecedor"),
    path("detalhar/fabricante/<int:pk>/", FabricanteDetail.as_view(), name="detalhar-fabricante"),
    path("detalhar/marca/<int:pk>/", MarcaDetail.as_view(), name="detalhar-marca"),
    path("detalhar/categoria/<int:pk>/", CategoriaDetail.as_view(), name="detalhar-categoria"),
    path("detalhar/cliente/<int:pk>/", ClienteDetail.as_view(), name="detalhar-cliente"),
    path("detalhar/funcionario/<int:pk>/", FuncionarioDetail.as_view(), name="detalhar-funcionario"),
    path("detalhar/produto/<int:pk>/", ProdutoDetail.as_view(), name="detalhar-produto"),

    #Ajax

    path("listar_produtos/", views.listar_produtos, name="listar_produtos"),
    path("buscar/cliente", ClienteAutocomplete.as_view(), name="buscar-cliente"),
    path("buscar/produto", ProdutoAutocomplete.as_view(), name="buscar-produto")
]

itohookahapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("paginas.urls")),
    path("", include("cadastros.urls")),
    path("", include("usuarios.urls")),
    path("__debug__", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paginas/urls.py
from django.urls import path
from .views import IndexView, SobreView, RelatoriosView

urlpatterns = [
    path("", IndexView.as_view(), name="pagina-inicial"),

    path("sobre", SobreView.as_view(), name="sobre"),

    path("relatorios", RelatoriosView.as_view(), name="relatorios"),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Fornecedor(models.Model):
    nome = models.CharField(max_length=50)
    telefone = models.CharField(max_length=15, verbose_name="Telefone")
    documento = models.CharField(max_length=18, help_text="Informe o CNPJ")

    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nome}"
    
class Fabricante(models.Model):
    nome = models.CharField(max_length=50)
    
    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nome}"

class Marca(models.Model):
    nome = models.CharField(max_length=50)
    fornecedor = models.ForeignKey(Fornecedor, on_delete=models.PROTECT)

    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nome}"
    
class Categoria(models.Model):
    nome = models.CharField(max_length=50)

    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nome}"

class Cliente(models.Model):
    nome = models.CharField(max_length=50, verbose_name="Nome")
    cpfCnpj = models.CharField(max_length=14, verbose_name="CPF", unique=True)
    telefone = models.CharField(max_length=15)
    endereco = models.CharField(max_length=300)
    cep = models.CharField(max_length=10, verbose_name="CEP")
    logradouro = models.CharField(max_length=100)
    numero = models.CharField(max_length=20, verbose_name="Número", null=True, blank=True)
    bairro = models.CharField(max_length=50, null=True, blank=True)
    cidade = models.CharField(max_length=50)

    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Nome: {self.nome} | CPF: {self.cpfCnpj} | Telefone: {self.telefone}"
    
class Funcionario(models.Model):
    nome = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    funcao = models.CharField(max_length=50)
    endereco = models.CharField(max_length=300)
    telefone = models.CharField(max_length=15)

    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Nome: {self.nome} | Função: {self.funcao}"
    
class Produto(models.Model):
    nome = models.CharField(max_length=50)
    valor = models.DecimalField(
        decimal_places=2, max_digits=9, verbose_name="Valor")
    quantidade = models.IntegerField(verbose_name="Quantidade", default=0)
    fornecedor = models.ForeignKey(
        Fornecedor, on_delete=models.PROTECT, help_text="Selecione o fornecedor")
    marca = models.ForeignKey(
        Marca, on_delete=models.PROTECT, help_text="Selecione a marca")
    categoria = models.ForeignKey(
        Categoria, on_delete=models.PROTECT, help_text="Selecione a categoria")
    imagem = models.ImageField(upload_to='imagens/', blank=True, null=True, verbose_name="Imagem")

    cadastrado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Nome: {self.nome} - Marca: {self.marca} - R${self.valor}"
    
class Pedido(models.Model):
    cliente = models.ForeignKey(
        Cliente, on_delete=models.PROTECT)
    valor_total = models.DecimalField(
        decimal_places=2, max_digits=9, verbose_name="Preço")

    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)


class ProdutoPedido(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    preco = models.DecimalField(
        decimal_places=2, max_digits=9, verbose_name="Preço")
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.produto.nome} ({self.quantidade})'

class Carrinho(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'Produto: {self.produto} | Qtd. {self.quantidade}'

    
#=======================================================================================
# Ajax 



 #Fazer um para Origem do Produto = importado ou não, da onde veio pa
 

cadastros/forms.py
from dal import autocomplete
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from .models import Carrinho, Pedido, Produto, Categoria, Fornecedor, Cliente
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column

class ProdutoForms(forms.ModelForm):
    preco = forms.DecimalField(decimal_places=2, max_digits=9, localize=True)

    class Meta:
        model = Produto
        fields = ["nome", "preco", "marca"]
    
class PedidoForms(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ["cliente"]
        widgets = {
            'cliente': autocomplete.ModelSelect2(
                url='buscar-cliente',
                attrs={
                    'data-placeholder': 'Informe o nome do cliente',
                    'data-minimum-input-length': 0,
                    'data-allow-clear': 'true',
                },
            )
        }

class CarrinhoForm(forms.ModelForm):
    class Meta:
            model = Carrinho
            fields = ["produto", "quantidade"]
            widgets = {
                'produto': autocomplete.ModelSelect2(
                    url='buscar-produto',
                    attrs={
                        'data-placeholder': 'Informe o nome do produto',
                        'data-minimum-input-length': 0,
                        'data-allow-clear': 'true',
                    },
                ),
            }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('produto', css_class='col-md-10'),
                Column('quantidade', css_class='col-md-2'),
            )
        )

class ProdutoFilterForm(forms.Form):
    nome = forms.CharField(required=False, label='Nome')
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all(), required=False, label='Categoria')
    fornecedor = forms.ModelChoiceField(queryset=Fornecedor.objects.all(), required=False, label='Fornecedor')

class PedidoFilterForm(forms.Form):
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), required=False, label="Cliente")
    valor_min = forms.DecimalField(required=False, label="Valor Mínimo", min_value=0, decimal_places=2)
    valor_max = forms.DecimalField(required=False, label="Valor Máximo", min_value=0, decimal_places=2)
    data_inicio = forms.DateField(required=False, label="Data de Início", widget=AdminDateWidget)
    data_fim = forms.DateField(required=False, label="Data de Fim", widget=AdminDateWidget)

cadastros/templates/cadastros/delete.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<h1 class="mt-5">{{titulo|default:"Deseja excluir?"}}</h1>

<style>
    tr, td {
        text-align: center;
    }
    .btn-purple {
        background-color: #6f42c1; /* Roxo */
        color: white;
    }
    .btn-orange {
        background-color: #ffbb00; /* Roxo */
        color: black;
    }
    .btn-green {
        background-color: #3d8b0f; /* Roxo */
        color: rgb(255, 255, 255);
    }
    .btn-grey {
        background-color: #838383; /* Roxo */
        color: rgb(255, 255, 255);
    }
</style>

<form action="" method="post">
    {% csrf_token %}

    <p>
        Tem certeza que deseja excluir este registro: <b>{{object}}</b>
    </p>

    <button type="button" class="btn btn-grey" onclick="history.back();">
        Voltar
    </button>

    <button type="submit" class="btn btn-danger">Excluir</button>
</form>

{% endblock %}

cadastros/templates/cadastros/form-cadastros.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}

<h3 class="mt-3 border-bottom mb-4 pb-2">
    {{ titulo|default:"Formulário de cadastro e edição" }}
</h3>

<style>
    tr, td {
        text-align: center;
    }
    .btn-purple {
        background-color: #6f42c1; /* Roxo */
        color: white;
    }
    .btn-orange {
        background-color: #ffbb00; /* Roxo */
        color: black;
    }
    .btn-green {
        background-color: #3d8b0f; /* Roxo */
        color: rgb(255, 255, 255);
    }
    .btn-grey {
        background-color: #838383; /* Roxo */
        color: rgb(255, 255, 255);
    }
</style>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{form|crispy}}

    <button type="submit" class="btn btn-green float-end">
        Salvar
    </button>

    <button type="button" class="btn btn-grey float-end" style="margin-right: 10px;" onclick="history.back();">
        Voltar
    </button>

    <br><br><br> 
       
</form>

{% endblock %}

{% block scripts %}

<!-- Importação do jQuery Mask Plugin -->
<script src="{% static 'js/jquery.mask.js' %}"></script>

<!-- Aplicar mascaras nos campos -->
<script>
    $(document).ready(function () {

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
            spOptions = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

        $('#id_telefone').mask(SPMaskBehavior, spOptions);

                var CpfCnpjBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '000.000.000-009' : '00.000.000/0000-009';
        },
            spOptions = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(CpfCnpjBehavior.apply({}, arguments), options);
                }
            };

        $('#id_cpfCnpj').mask(CpfCnpjBehavior, spOptions);

    });
</script>

<!-- Aplicar máscaras nos campos -->
<script>
    $(document).ready(function () {

        $("#x, #y, .z").attr("type", "text");
        $("#x, #y, .z").addClass("numeros");

        $("#id_cpf").mask("000.000.000-00");
        $("#id_cep").mask("00000-000");
        $("input[name*=data_]").mask("00/00/0000");

        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
        },
            spOptions = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

        $('#id_telefone').mask(SPMaskBehavior, spOptions);


        var CpfCnpjBehavior = function (val) {
            return val.replace(/\D/g, '').length <= 11 ? '000.000.000-009' : '00.000.000/0000-00';
        },
            cpfcnpjOptions = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(CpfCnpjBehavior.apply({}, arguments), options);
                }
            };

        $('#id_cpfCnpj').mask(CpfCnpjBehavior, cpfcnpjOptions);


        $("form").submit(function (e) {

            $.each(".numeros", function (i, valor) {
                valor = valor.replace(".", "").replace(",", ".");
                $(this).attr("type", "number");
                $(this).val(valor);
            });

        });

        // Consulta o CEP com Ajax
        $("#id_cep").blur(function (e) {

            // Limpa os campos
            $("#id_logradouro").val("");
            $("#id_bairro").val("");
            $("#id_cidade").val("");

            var cep = $("#id_cep").val();

            if (cep.length < 9) {
                return;
            }

            $("#div_id_cep").append(
                '<section class="dots-container">' +
                '<div class="dot"></div>' +
                '<div class="dot"></div>' +
                '<div class="dot"></div>' +
                '<div class="dot"></div>' +
                '<div class="dot"></div>' +
                '</section>'
            );

            var url = "https://viacep.com.br/ws/" + cep + "/json/";

            $.getJSON(url, "",
                function (data, textStatus, jqXHR) {

                    if (data.erro != true) {
                        $("#id_logradouro").val(data.logradouro);
                        $("#id_bairro").val(data.bairro);
                        $("#id_cidade").val(data.localidade + "/" + data.uf);
                        $("#id_numero").focus();
                    }


                }
            );

        });

    });
</script>

{% endblock %}

cadastros/templates/cadastros/form-carrinho.html
{% extends "paginas/modelo.html" %}

{% load static %}

<!-- Carrega o filtro de multiplicacao do valor total -->
{% load meus_filtros %}

{% load crispy_forms_tags %}

{% block conteudo %}

<div class="row align-items-center mt-3">
    <div class="col-md-8">
        <h3>{{titulo|default:"Formulário"}}</h3>
    </div>
    <div class="col-md-4 d-flex justify-content-end gap-2">
        <a href="{% url 'cadastrar-carrinho' %}" class="btn btn-purple">
            Adicionar Item
        </a>
        <a href="{% url 'cadastrar-pedido' %}" class="btn btn-orange">
            Fechar Carrinho
        </a>
    </div>
</div>


<hr>

<style>
    tr, td {
        text-align: center;
    }
    .btn-purple {
        background-color: #6f42c1; /* Roxo */
        color: white;
    }
    .btn-orange {
        background-color: #ffbb00; /* Roxo */
        color: black;
    }
    .btn-green {
        background-color: #3d8b0f; /* Roxo */
        color: rgb(255, 255, 255);
    }
    .btn-grey {
        background-color: #838383; /* Roxo */
        color: rgb(255, 255, 255);
    }
</style>

<!-- Campo de selecionar o produto -->
<form action="" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-10">
            {{ form.produto|as_crispy_field }}
        </div>
        <div class="col-md-2">
            {{ form.quantidade|as_crispy_field }}
        </div>
    </div>

<div class="table-responsive-lg">
    <h4 class="mt-5 border-bottom mb-4 pb-2">Itens Adicionados</h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Código</th>
                <th>Produto</th>
                <th>Quantidade</th>
                <th>Preço Unitário</th>
                <th>Valor Total</th>
            </tr>
        </thead>
        <tbody>
            {% for obj in carrinho %}
            <tr class="">
                <td>{{ obj.pk }}</td>
                <td>{{ obj.produto.nome }}</td>
                <td>{{ obj.quantidade }}</td>
                <td>{{ obj.produto.valor }}</td>
                <td>R${{ obj.quantidade|valor_total_item_carrinho:obj.produto.valor }}</td>
                <td>
                    <div class="dropdown">
                        <a class="btn btn-sm btn-outline-secondary dropdown-toggle" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-gear"></i>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item text-primary" href="{% url 'editar-carrinho' obj.pk %}">
                                    <i class="bi bi-pencil-square"></i>Editar</a></li>
                            <li><a class="dropdown-item text-danger" href="{% url 'excluir-carrinho' obj.pk %}">
                                    <i class="bi bi-trash"></i> Excluir</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% empty %}
            <tr>
                <th colspan="100%" style="font-weight: bold; color: red; text-align: center;">Nenhum item adicionado ao Carrinho de Compras.</th>
            </tr>
            {% endfor %}
            <tr>
                <td><strong>Total</strong></td>
                <td></td>
                <td>{{ total_itens }}</td>
                <td></td>
                <td><strong>R${{ valor_total }}</strong></td>
                <td></td>
            </tr>
        </tbody>
    </table>
</div>

<!-- Botão de salvar -->

    <br>
    <div class="col-md-12 d-flex align-items-center justify-content-end">
        <!-- Botão Voltar -->
        <button type="button" class="btn btn-grey" style="margin-right: 10px;" onclick="history.back();">
            Voltar
        </button>
        <!-- Botão Salvar -->
        <button type="submit" class="btn btn-green float-end">
            {{ descricao_botao|default:"Salvar" }}
        </button>
    </div>
</form>

<!-- Botão de Limpar Carrinho -->
<form action="" method="post" style="display: inline;">
    {% csrf_token %}
    <div class="col-md-12 d-flex align-items-center justify-content-end mt-2">
        <button type="submit" name="limparcarrinho" class="btn btn-danger">
            Limpar Carrinho
        </button>
    </div>
</form>

{% endblock %}

{% block scripts %}
{{ form.media }}
{% endblock %}

cadastros/templates/cadastros/form-login.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
    <div class="container" style="margin-left: 220px; margin-top: 100px;">
        <div class="row align-items-center mt-5">
            <div class="col-md-4 text-center mb-4">
                <img src="{% static 'img/logodois-vetorizada.png' %}" alt="Logo" class="img-fluid mt-4">
            </div>
            <div class="col-md-3">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-dark mt-4 btn-senha" type="button">
                        <i class="bi bi-eye-slash"></i>
                    </button>
                    <button type="submit" class="btn btn-success btn-block mt-4">
                        Entrar
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
<script>

    $(document).ready(function () {

        $(".btn-senha").click(function (e) {
            var tipo = $("#id_password").attr("type");
            if(tipo == "password"){
                $("#id_password").attr("type", "text");
            } else {
                $("#id_password").attr("type", "password");
            }
        });

    });

</script>
{% endblock %}

cadastros/templates/cadastros/form.html
{% extends "paginas/modelo.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}

<h3 class="mt-3 border-bottom mb-4 pb-2">
    {{ titulo|default:"Formulário de cadastro e edição" }}
</h3>

<form action="" method="post">
    {% csrf_token %}

    {{form|crispy}}

    <button type="submit" class="btn btn-success float-end">
        Salvar
    </button>
</form>

{% endblock %}